### PR TITLE
Support for dai.ly urls

### PR DESCRIPTION
**Pull request by gionaf**
Added support for Dailymotion shorturls
Fixed method names in readme

### CODE REVIEW

**Comment by dereuromark** [comment]
A basic test case would be ideal. If not no big problem.

**Comment by gionaf** [comment]
Oh sorry. I should add it to videos.csv and MediaEmbedTest.php right?

**Comment by dereuromark** [comment]
jep

**Comment by gionaf** [comment]
Not sure i did it right as i'm not using the library with Composer...

**Comment by dereuromark** [comment]
Awesome, thanks!

**Pull request merged**
