### PR TITLE
Added support for Bit.Tube

### PR DESCRIPTION
**Pull request by nifflerco**
Wasn't sure about embed src as Bit.Tube doesn't seem to have that anywhere.

### CODE REVIEW

**Comment by dereuromark** [comment]
Cs needs fixing

**Comment by nifflerco** [comment]
> Cs needs fixing

Any chance you could provide a bit more details on the issue? Not exactly sure what is CS

**Comment by nifflerco** [comment]
Sorted it out..

**Comment by dereuromark** [comment]
Your IDE should usually trim right the modified lines. 
Thanks for the contribution!

**Pull request merged**
