### PR TITLE
url-match regexes should'nt contain ^ and $

### PR DESCRIPTION
**Pull request by jhuet**
Because starting and ending chars are already forced [here](https://github.com/dereuromark/MediaEmbed/blob/master/src/MediaEmbed/MediaEmbed.php#L115) and [there](https://github.com/dereuromark/MediaEmbed/blob/master/src/MediaEmbed/MediaEmbed.php#L130).

### CODE REVIEW

**Comment by dereuromark** [comment]
Thx!

**Comment by jhuet** [comment]
@dereuromark do you think you could tag a new version with this PR ? I'd like to have it without cloning dev-master thru composer. Thanks !

**Comment by dereuromark** [comment]
Done :)

**Comment by jhuet** [comment]
So quick ! Thank you :)

**Comment by jhuet** [comment]
Hi @dereuromark, sorry to bother you again, but the 0.2.1 tag doesn't seem to have been [propagated to packagist](https://packagist.org/packages/dereuromark/media-embed).

**Comment by dereuromark** [comment]
Thx again, I fixed the auto-update. All good now.

**Comment by jhuet** [comment]
:+1:

**Pull request merged**
